version: "3.7"

services:

  mysql:
    container_name: mysql
    image: mysql:8.0.21
    # image: mariadb:10.4
    restart: on-failure
    env_file: .env
    ports:
    - 3306:3306
    volumes:
    - mysql:/var/lib/mysql
    - ./sql:/sql
    networks:
    - default

volumes:
  mysql:
